spring:
  application:
    name: service-oss

  cloud:
    nacos:
      discovery:
        server-addr: 116.204.65.192:8848
    sentinel:
      transport:
        # 服务监控端口
        dashboard: localhost:8080
        # 默认 8719，假如被占用了会自动从 8719 开始依次 +1 扫描，直至找到未被占用的端口
        port: 8721

    alicloud:
      access-key: LTAI5tRpWutP7Kdvw3ZKdRez
      secret-key: KYFqX3J2zDw8suaAIMZvxObgIVMYSA
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-chenle

server:
  port: 8084
